### ISSUE TITLE
Grid - Gérée avec une liste de rectangle 

### ISSUE THREAD

**Issue by Vskilet** [UTBroM/2COA#17]
(Grid - implements DrawableObject) Le rectangle peut être une image mais doit être bien positionné

**Comment by Vskilet** [comment]
Je pense que ce ticket est réglé non ? 
Commit: 7bfdaa22668ef5529333dd3f1e1ab5b831623ac9 et a3166d6467a043bb576bcb8da34f636d02729420

**Comment by fstaine** [comment]
Je l'ai pas fermé car je ne savais pas si on allait avoir à le retoucher par la suite pour modifier les coordonnés que j'ai mis pour l'instant mais ca ne sera pas une grosse modification à faire
