### ISSUE TITLE
Grid - Implémenter le beDrawn

### ISSUE THREAD

**Issue by Vskilet** [UTBroM/2COA#18]
(Grid implements DrawableObject) Penser à gérer l'aspect graphique !

**Comment by fstaine** [comment]
Pour ne pas avoir à saisir 2 fois les coordonnés des rectangles, on peut pas mettre Grid dans tileListManager,  les valeurs de padx, rectSizeX, ... seraient stockées dans tileListManager et on instancie Grid avec.
Et comme ca on peut aussi les avoir pour initialiser goodPosition

**Comment by Vskilet** [comment]
On peut retrouver les débuts ici : 8edc09a099da33c87a685f43499798218af4f1b8
