### ISSUE TITLE
Bomb - Conception class

### ISSUE THREAD

**Issue by Vskilet** [UTBroM/2COA#19]
(Bomb extends Tile implements DrawableObject ---> vérifier si implements nécessaire)
Penser à se coordonner avec tout le monde pour comprendre son fonctionnement

**Comment by nyanloutre** [comment]
ouais le implements je suis pas sur, Tile le fait déjà non ?

**Comment by Whiax** [comment]
Issue: Désactiver la bombe si elle fusionne (Supprimer la partie bombe du Tile ? Voir si c'est faisable)

**Comment by Vskilet** [comment]
Tellement fini
