### ISSUE TITLE
TileListManager - Constructeur --> goodPosition

### ISSUE THREAD

**Issue by Vskilet** [UTBroM/2COA#22]
(TileListManager --> gère la list de tile et leurs mouvements)
Les constructeurs calculent les goodPosition (la liste des positions où chaque tile sera situé)

**Comment by nyanloutre** [comment]
Tu donne un nom au constructeur lol
edit: goodPosition c'est une classe ?
edit2: ah no j'ai trouvé c'est le nom de la variable, le titre de l'issue était un peu ambigu :smile:

**Comment by fstaine** [comment]
Personne n'a commencé ?
Par ce qu'il le faut pour pouvoir lancer le projet du coup je le fais !

**Comment by nyanloutre** [comment]
attend je vais voir ça :smiley:

**Comment by nyanloutre** [comment]
Tu peut venir sur ts ? cl4ptp.ddns.net

**Comment by fstaine** [comment]
j'y suis !
