### ISSUE TITLE
TileListManager - void InitMovement(Direction)

### ISSUE THREAD

**Issue by Vskilet** [UTBroM/2COA#25]
(TileListManager --> gère la list de tile et leurs mouvements)
Lance le déplacement et calcul le point d'arrivé (dans le keypressed) $PAUL

**Comment by nyanloutre** [comment]
Faut juste l'objet TileList quand même

**Comment by nyanloutre** [comment]
Une question quand même : on modifie direct les tuiles on on retourne une nouvelle TileList avec les nouvelles positions ?
Faut voir pour animer en fait du coup car si on modifie direct les coordonnées c'est chaud. Alors que si on renvoie une nouvelle TileList modifiée on peut comparer izi

**Comment by nyanloutre** [comment]
Dans dans cette méthode on va appeler une autre qui résout les combinaisons de tuiles et qui renverra une tuile (avec la nouvelle valeur) ou 2 tuiles si elles n'avaient pas la même valeur. Du coup le problème est comment renvoyer 2 tuiles ou une seule

**Comment by Vskilet** [comment]
Il faut le définir mais effectivement je pense que tu as raison c'est plus simple de renvoyer une nouvelle TileList. En plus Fusion pourrait renvoyer une nouvelle TileList pour éviter de retourner 2 tuiles.

**Comment by nyanloutre** [comment]
Tile est un peu ambigu quand même : il stocke le point d'arrivée. C'est bizarre non ?
Ah ou alors ça peut être très cool car ce évite d'envoyer une nouvelle tileliste, il suffira de constament animer la tuile pour la faire aller vers ce point qui changera dynamiquement en fonction des mouvements

**Comment by nyanloutre** [comment]
du coup on peu modifier direct les tiles

**Comment by nyanloutre** [comment]
Donc la méthode de combinaison a qu'a renvoyer null si elle se combinent pas et on fait un bête test

**Comment by Whiax** [comment]
Cette méthode a pour but de donner à chaque Tile sa Tile d'arrivée si elle doit fusionner et sinon son point d'arrivée, ni plus ni moins ^^
On pourra discuter de comment faire Vendredi ou avant si besoin est. Et on peut toujours modifier TileList pour le faire correspondre à nos souhaits si c'est nécessaire.

**Comment by Vskilet** [comment]
Faut pas oublier de l'optimiser nyanloutre
