### ISSUE TITLE
Faire une petite entrée au wiki pour expliquer vite fais certaines chose

### ISSUE THREAD

**Issue by nyanloutre** [UTBroM/2COA#28]
Du genre comment vous avez fait les rectangles avec des coins arrondis ou géré tel ou tel truc.
Ça nous fera gagner du temps pour le rapport

**Comment by Vskilet** [comment]
Vous avez le rapport ici : https://sene.ovh/owncloud/index.php/s/9cIoMaSe4VnRQYo
