### ISSUE TITLE
Comptabilisation des Points

### ISSUE THREAD

**Issue by fstaine** [UTBroM/2COA#35]
Fusion de 2 et de 2 => Donne 4 points 
Affichage du score en haut à droite de la fenêtre

**Comment by nyanloutre** [comment]
Je vais essayer de le faire si tu n'a pas commencé

**Comment by fstaine** [comment]
Vas-y fais le :-)
Mais fais le seulement si tu as le temps et si tu as fini d'optimiser ta fonction InitMovement

**Comment by Vskilet** [comment]
Fait en bd785644d09e79a95374c8bf916531a9354fa7e1
