### ISSUE TITLE
Revenir en arrière

### ISSUE THREAD

**Issue by fstaine** [UTBroM/2COA#36]
Possibilité contre des points de revenir un tour en arrière

**Comment by nyanloutre** [comment]
Trop cheaté, le but est de faire 2048 pas d'avoir des points, faut juste limiter à un certain nombre d'annulation dans la partie. Une partie de ce type serais vraiment facile ou alors fixer un objectif plus haut du type 4096.
Sinon ça voudrais dire que plus on avance plus on peut reculler :smile: (autant permettre à l'infini dans ce cas)

**Comment by Whiax** [comment]
Broaf on s'en fiche, l'idée c'est juste de rajouter des fonctionnalités, et au pire ça donne un intérêt aux points (qui servent à rien dans le jeu original)

**Comment by fstaine** [comment]
Il suffit que ca coûte des points de revenir en arrière...

**Comment by Whiax** [comment]
Peut être que dans le initMovement, avant le tileMatrix = new TileMatrix(nextTileMatrix), il faudrait rajouter:  precTileMatrix = new TileMatrix(tileMatrix)
A test, mais pas garantie

**Comment by Vskilet** [comment]
Closed par e15fd81b4c0a4e6fb74636cffdf2ff56228f2869
