### ISSUE TITLE
Bomb - Gestion fusion

### ISSUE THREAD

**Issue by fstaine** [UTBroM/2COA#41]
Transformer une Bomb en Tile classique lorsqu'elle a fusionnée (Elle se supprime uniquement si c'est la Tile qui se déplace qui est la bombe et le Tile d'arrivée qui est une Tile classique)

**Comment by Whiax** [comment]
A faire dans manage fusion

**Comment by fstaine** [comment]
J'ai toujours le même problème moi avec les Tiles qui ne se suppriment pas lorsque la Tile d'arrivée est une bombe

**Comment by fstaine** [comment]
Fail de fermeture en KDO !

**Comment by Vskilet** [comment]
Fermeture : ae376298d6de468f7301a7faeee7a92fbd5ebc23
